### PR TITLE
Update xpk.py

### PR DESCRIPTION
**Pull request by sadikneipp**
Remove server argument from proxy server arguments.

## Fixes / Features
- Without this change, the proxy server was not starting up for me. I'd get an unknown argument error.

## Testing / Documentation
This unblocked me from running a workload.

### CODE REVIEW

**Review by Obliviour — COMMENTED** [review]
Thanks @sadikneipp for the fast change!

1. Nit to change the PR Name to be more specific. 

2. @RoshaniN can you confirm if this flag is needed for other aspects -- is this the right fix for the issue?

**Comment by RoshaniN** [comment]
Hey Sadi,
I am curious to know if any logic around this argument was recently changed in Pathways, as I did not face this issue.

**Comment by Obliviour** [comment]
Looking at the Build Test failure, you may need to create a PR from a branch instead of a fork. I provided you permissions to do this, just in case.

**Review by RoshaniN — CHANGES_REQUESTED** [review]
Thanks for the change, Sadi!

Looks like the flag fails after adding cl/607802178, which will be merged soon. Currently this flag is not super useful either, so I see no issues removing it.

 Changes are GTG once the branch is rebased onto main .

**Comment by sadikneipp** [comment]
Since it's such a small change @RoshaniN aligned with me to incorporate this PR in #100 . I'll close this PR.

**Pull request closed without merging**
